###
POST http://localhost:9999/editor/save/character
Content-Type:application/json

{
  "name": "",
  "description": "",
  "image": ""
}

###
POST http://localhost:9999/editor/save/comics
Content-Type:application/json

{
  "title": "",
  "description": "",
  "image": ""
}

###
GET http://localhost:9999/characters/84bcff5e-2899-49a9-9190-7b018d861282/comics

###

GET http://localhost:9999/comics

###
POST http://localhost:9999/editor/bind/character/84bcff5e-2899-49a9-9190-7b018d861282
Content-Type:application/json

[
  {
    "id": "f3b01035-f3ec-4740-bdd8-8e086ea2e239",
    "title": "",
    "description": "",
    "image": ""
  },
  {
    "id": "791e0f8d-075c-422f-bba1-ab5c024fac55",
    "title": "",
    "description": "",
    "image": ""
  }
]

###
DELETE http://localhost:9999/editor/remove/comics/f3b01035-f3ec-4740-bdd8-8e086ea2e239

###