###
POST http://localhost:9999/characters/save
Content-Type:application/json

{
  "name": "one",
  "description": "one",
  "image": ""
}

###
POST http://localhost:9999/comics/save
Content-Type:application/json

{
  "title": "",
  "description": "",
  "image": ""
}

###
GET http://localhost:9999/characters?page=2&count=5

###

GET http://localhost:9999/comics

###
POST http://localhost:9999/characters/bind/84bcff5e-2899-49a9-9190-7b018d861282
Content-Type:application/json

[
  {
    "id": "f3b01035-f3ec-4740-bdd8-8e086ea2e239",
    "title": "",
    "description": "",
    "image": ""
  },
  {
    "id": "791e0f8d-075c-422f-bba1-ab5c024fac55",
    "title": "",
    "description": "",
    "image": ""
  }
]

###
DELETE http://localhost:9999/comics/remove/f3b01035-f3ec-4740-bdd8-8e086ea2e239

###