###
POST http://localhost:9999/editor/save/character
Content-Type:application/json

{
  "name": "",
  "description": "",
  "image": ""
}

###
POST http://localhost:9999/editor/save/comics
Content-Type:application/json

{
  "title": "",
  "description": "",
  "image": ""
}

###
GET http://localhost:9999/characters/05841a81-b546-4113-a9e7-5054ffce0cdf/comics

###
#05841a81-b546-4113-a9e7-5054ffce0cdf
#a44cb47c-5c83-4662-b322-53e9de7cb8c2

GET http://localhost:9999/comics

###
POST http://localhost:9999/editor/bind/character/05841a81-b546-4113-a9e7-5054ffce0cdf
Content-Type:application/json

[
  {
    "id": "6c99d5b0-9430-46ef-8f6f-3753a76e2a61",
    "title": "Infinity War 2",
    "description": "",
    "image": ""
  }
]

###